<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWwt9DNY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWwt9DNY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWwt9DNY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWwt9DNY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWwt9DNY\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wwt9DNY',
    'container.build_id' => '66502a76',
    'container.build_time' => 1730885905,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWwt9DNY');
